/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6edadf57-cb39-484a-8d99-872755e8c8e4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_P7DrWOJBo",
    "aws_user_pools_web_client_id": "59asmdqmg8avqjh3ohrj848uvr",
    "oauth": {}
};


export default awsmobile;
